# scala-async-atry
Support await under try/catch in scala-async
